const fortunes = [
{ number: 1, description: "Is everything random? Or is it just a matter of your quantum interpretation?" },
{ number: 2, description: "Quantum means smallest quantity. You cannot be any less than what you are." },
{ number: 3, description: "Entangled particles are everywhere, so are we ever really alone?" },
{ number: 4, description: "My personal opinion is that the world is even weirder than what quantum physics tells us. - Anton Zeilinger" },
{ number: 5, description: "The universe is like a library in which the words are atoms. Just look at what has been written! - Heinz R. Pagels (adapted)" },
{ number: 6, description: "The world of quantum mechanics is not a world of objects: it is a world of events. - Carlo Rovelli" },
{ number: 7, description: "There has been a quantum leap technologically in our age, but unless there is another quantum leap in human relations, unless we learn to live in a new way towards one another, there will be a catastrophe. - Albert Einstein" },
{ number: 8, description: "We must believe that we are gifted for something and that this thing must be attained. - Marie Curie" },
{ number: 9, description: "An expert is a person who has made all the mistakes that can be made in a very narrow field. - Niels Bohr" },
{ number: 10, description: "If you want to be respected, do not disrespect others. - Shirley Ann Jackson" },
{ number: 11, description: "Treasure your curiosity and nurture your imagination. - Shirley Ann Jackson" },
{ number: 12, description: "You cannot hope to build a better world without improving the individuals. - Marie Curie" },
{ number: 13, description: "Life need not be easy, provided only that it is not empty. - Lise Meitner" },
{ number: 14, description: "I don't fear death because I don't fear anything I don't understand. - Hedy Lamarr" },
{ number: 15, description: "Let us choose for ourselves our path in life, and let us try to strew that path with flowers. - Emilie du Chatelet" },
{ number: 16, description: "Mankind has made giant steps forward. However, what we know is really very, very little compared to what we still have to know. - Fabiola Gianotti" },
{ number: 17, description: "In a spiral galaxy, the ratio of dark-to-light matter is about a factor of 10. That's probably a good number for the ratio of our ignorance-to-knowledge. We're out of kindergarten, but only in about third grade. - Vera Rubin" },
{ number: 18, description: "If you know you are on the right track, if you have this inner knowledge, then nobody can turn you off... no matter what they say. - Barbara McClintock" },
{ number: 19, description: "The future never just happened. It was created. - Mae Jemison" },
{ number: 20, description: "Science and everyday life cannot and should not be separated. - Rosalind Franklin" },
{ number: 21, description: "Give the world the best you've got. And you will get kicked in the teeth. Give the world the best you've got anyway. - Hedy Lamarr" },
{ number: 22, description: "Try everything. Join everything. Meet everybody. That's the secret of life. - Hedy Lamarr" },
{ number: 23, description: "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle. - Albert Einstein" },
{ number: 24, description: "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world. - Albert Einstein" },
{ number: 25, description: "Imagination is everything. It is the preview of life's coming attractions. - Albert Einstein" },
{ number: 26, description: "If you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales. - Albert Einstein" },
{ number: 27, description: "Anyone who has never made a mistake has never tried anything new. - Albert Einstein" },
{ number: 28, description: "Try not to become a person of success. Rather become a person of value. - Albert Einstein (adapted)" },
{ number: 29, description: "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking. - Albert Einstein" },
{ number: 30, description: "Once you can accept the universe as matter expanding into nothing that is something, wearing stripes with plaid comes easy. - Albert Einstein" },
{ number: 31, description: "The best way to cheer yourself is to cheer somebody else up. - Albert Einstein" },
{ number: 32, description: "Whoever is careless with the truth in small matters cannot be trusted with important matters. - Albert Einstein" },
{ number: 33, description: "What is right is not always popular and what is popular is not always right. - Albert Einstein" },
{ number: 34, description: "Peace cannot be kept by force; it can only be achieved by understanding. - Albert Einstein" },
{ number: 35, description: "In the middle of difficulty lies opportunity. - Albert Einstein" },
{ number: 36, description: "Time is an illusion. - Albert Einstein" },
{ number: 37, description: "You must be willing to give up what you are in order to become what you will be. - Albert Einstein (adapted)" },
{ number: 38, description: "Love is a better master than duty. - Albert Einstein" },
{ number: 39, description: "Once we accept our limits, we go beyond them. - Albert Einstein" },
{ number: 40, description: "If you want to live a happy life, tie it to a goal, not to people or things. - Albert Einstein" },
{ number: 41, description: "I'd rather be an optimist and a fool than a pessimist and right. - Albert Einstein" },
{ number: 42, description: "So long, and thanks for all the fish. - Douglas Adams, The Hitchhiker's Guide to the Galaxy" },
{ number: 43, description: "The only thing that you absolutely have to know, is the location of the library. - Albert Einstein" },
{ number: 44, description: "Only those who attempt the absurd can achieve the impossible. - Albert Einstein" },
{ number: 45, description: "You can never solve a problem on the level on which it was created. - Albert Einstein" },
{ number: 46, description: "Look deep into nature, and then you will understand everything better. - Albert Einstein" },
{ number: 47, description: "Weakness of attitude becomes weakness of character. - Albert Einstein" },
{ number: 48, description: "A true genius admits that they know nothing. - Albert Einstein" },
{ number: 49, description: "The most beautiful thing we can experience is the mysterious. It is the source of all true art and all science. - Albert Einstein" },
{ number: 50, description: "I believe in intuitions and inspirations...I sometimes FEEL that I am right. I do not KNOW that I am. - Albert Einstein" },
{ number: 51, description: "The only real valuable thing is intuition. - Albert Einstein" },
{ number: 52, description: "The human mind, no matter how highly trained, cannot grasp the universe. We are in the position of a little child, entering a huge library whose walls are covered to the ceiling with books in many different tongues. - Albert Einstein" },
{ number: 53, description: "A person starts to live when they can live outside themselves. - Albert Einstein (adapted) " },
{ number: 54, description: "Look for what is, and not for what you think should be. - Albert Einstein (adapted)" },
{ number: 55, description: "The only sure way to avoid making mistakes is to have no new ideas. - Albert Einstein" },
{ number: 56, description: "At least once a day, allow yourself the freedom to think and dream for yourself. - Albert Einstein" },
{ number: 57, description: "Everybody is a genius. But if you judge a fish by its ability to climb a tree it will live its whole life believing that it is stupid. - Albert Einstein" },
{ number: 58, description: "Our separation from each other is an optical illusion. - Albert Einstein" },
{ number: 59, description: "Adversity introduces you to yourself. - Albert Einstein (adapted)" },
{ number: 60, description: "Always do what's right; this will gratify some and astonish the rest. - Albert Einstein" },
{ number: 61, description: "Weak people revenge. Strong people forgive. Intelligent people ignore. - Albert Einstein" },
{ number: 62, description: "The most important decision we make is whether we believe we live in a friendly or hostile universe. - Albert Einstein" },
{ number: 63, description: "Concerning matter, we have been all wrong. What we have called matter is energy, whose vibration has been so lowered as to be perceptible to the senses. There is no matter. - Albert Einstein" },
{ number: 64, description: "There is nothing known as perfect. It's only those imperfections which we choose not to see! - Albert Einstein" },
{ number: 65, description: "Only morality in our actions can give beauty and dignity to life. - Albert Einstein" },
];

export default fortunes;